<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <artifactId>shinden-enums</artifactId>
    <build>
        <plugins>

            <!-- 1. Generowanie pliku enuma w fazie generate-sources -->
            <plugin>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=studio</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=Studio</argument>
                                <argument>translationKeyPrefix=tags.studio</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=studio</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-studio-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=genre</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=Genre</argument>
                                <argument>translationKeyPrefix=tags.genre</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=genre</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-genre-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=targetgroup</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=TargetGroup</argument>
                                <argument>translationKeyPrefix=tags.target-group</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=targetgroup</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-target-group-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=entity</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=CharacterType</argument>
                                <argument>translationKeyPrefix=tags.character-type</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=entity</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-character-type-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=place</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=PlaceAndTime</argument>
                                <argument>translationKeyPrefix=tags.place-and-time</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=place</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-place-and-time-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=tag</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=Other</argument>
                                <argument>translationKeyPrefix=tags.other</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=tag</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-other-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=productiontype</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=ProductionType</argument>
                                <argument>translationKeyPrefix=tags.production-type</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=productiontype</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-production-type-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=serialization</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=Publisher</argument>
                                <argument>translationKeyPrefix=tags.publisher</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=serialization</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-publisher-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>path=source</argument>
                                <argument>classPackage=com.github.kosmateus.shinden.enums.tag</argument>
                                <argument>className=SourceMaterial</argument>
                                <argument>translationKeyPrefix=tags.source-material</argument>
                                <argument>generatedSourcesPath=${project.build.directory}/generated-sources/tags
                                </argument>
                                <argument>tagType=source</argument>
                                <argument>queryParameter=tag</argument>
                                <argument>animeSearchQueryParameter=genres</argument>
                                <argument>
                                    translationFile=shinden-enums/target/generated-sources/resources/tags-translation.yaml
                                </argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <mainClass>com.github.kosmateus.shinden.enums.generator.EnumGenerator</mainClass>
                        </configuration>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <id>generate-source-material-tag</id>
                        <phase>generate-sources</phase>
                    </execution>
                </executions>
                <groupId>org.codehaus.mojo</groupId>
                <version>3.1.0</version>
            </plugin>

            <plugin>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/tags</source>
                            </sources>
                        </configuration>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <id>add-generated-sources</id>
                        <phase>generate-sources</phase>
                    </execution>
                </executions>
                <groupId>org.codehaus.mojo</groupId>
                <version>3.3.0</version>
            </plugin>

            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <artifactId>lombok</artifactId>
                            <groupId>org.projectlombok</groupId>
                            <version>1.18.34</version>
                        </path>
                    </annotationProcessorPaths>
                    <source>8</source>
                    <target>8</target>
                </configuration>
                <groupId>org.apache.maven.plugins</groupId>
                <version>3.8.1</version>
            </plugin>

            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}/generated-sources/resources</directory>
                                    <includes>
                                        <include>**/*.yaml</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                        <goals>
                            <goal>resources</goal>
                        </goals>
                        <id>add-generated-yaml</id>
                        <phase>generate-resources</phase>
                    </execution>
                </executions>
                <groupId>org.apache.maven.plugins</groupId>
                <version>3.2.0</version>
            </plugin>

        </plugins>
    </build>

    <dependencies>
        <dependency>
            <artifactId>shinden-commons</artifactId>
            <groupId>com.github.kosmateus</groupId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
    <modelVersion>4.0.0</modelVersion>
    <name>Shinden Enums</name>

    <packaging>jar</packaging>

    <parent>
        <artifactId>shinden4j</artifactId>
        <groupId>com.github.kosmateus</groupId>
        <version>1.0.0</version>
    </parent>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
